# Случайные числа

## Случайность и её философский аспект

Всю классическую эпоху естественных наук преобладал [детерминизм](https://ru.wikipedia.org/wiki/%D0%94%D0%B5%D1%82%D0%B5%D1%80%D0%BC%D0%B8%D0%BD%D0%B8%D0%B7%D0%BC), согласно которому в окружающей нас реальности отсутствует элемент случайности, все процессы природы предопределены, а кажущаяся нам случайность обусловлена неполнотой наших знаний. Эту позицию очень хорошо иллюстрирует высказывание Эйнштейна "бог не играет в кости": если бы нам было с абсолютной точностью известны положение и скорости кубика в момент броска, то мы могли бы точно рассчитать, на какую грань этот кубик приземлится. Согласно детерминизму тоже самое верно и о любой другой физической системе, ни в какой момент времени случайность не играет ни какой роли. 

С тех пор наука значительно продвинулась и детерминистическая картина мира сменилась на индетерминистическую. Например, квантовая механика предполагает фундаментальную роль вероятности в законах природы, процесс радиоактивного распада вещества моделируется законами с вероятностной природой. Это приводит нас к тому, что так как случайность --- неотъемлемая составляющая окружающего нас мира, то иногда ученные вынужденны подстраивать методологию своих исследований в соответствии. 

Кроме физики случайные модели используются также для анализа экономических/социальных процессов, теории игр, в численных методах типа Монте-Карло и в других областях деятельности человека. Также многие методы криптографии опираются на элементы случайности, что добавляет информационную безопасность в ту же категорию. Это всё приводит нас к необходимости генерации случайных чисел.

```{note}
Если вас интересует философская сторона вопроса, то автор курса рекомендует к прочтению статью "Об облаках и часах" Карла Поппера. 
```

## Псевдослучайность

Итак, согласно современным физическим теориям можно получать поистине случайные числа, наблюдая, например, за квантовыми системами или за процессом радиоактивного распада. Однако получение случайных чисел таким образом оказывается очень трудоемким процессом. В связи с этим вместо случайных числе на практике используют **псевдослучайные**.

Последовательность чисел называется **псевдослучайной**, если она является результатом **детерминированных и воспроизводимых** вычислений, но по её статистическим свойствам она **похожа на случайную**. 

В качестве примера сгенерируем три псевдослучайных числа. За генерацию псевдослучайных чисел в `python` отвечает модуль [random](https://docs.python.org/3/library/random.html). Вызов функции [random.random](https://docs.python.org/3/library/random.html#random.random) генерирует одно действительное псевдослучайное число в полуинтервале $[0, 1)$. 

In [4]:
import random

def random_numbers(n):
    result = []
    for i in range(n):
        result.append(random.random())
    return result

x = random_numbers(5)
print(x)

[0.8921795677048454, 0.08693883262941615, 0.4219218196852704, 0.029797219438070344, 0.21863797480360336]


Выше написана функция `random_numbers`, которая генерирует список из $n$ псевдослучайных чисел. Эта функция используется для того, чтобы получить последовательность из 5 псевдослучайных чисел. 

Если анализировать эту последовательность, то в ней практически невозможно обнаружить закономерность. В этом и заключается "похожесть на случайность": хорошо сгенерированную последовательность псевдослучайных чисел сложно (практически невозможно) отличить от последовательности поистине случайных чисел. Именно это и позволяет заменить случайные числа на псевдослучайные на практике.

```{note}
За последние десятилетия разработано огромное количество алгоритмов генерации псевдослучайных чисел. Однако все они имеют ограничения на длину последовательности: все генераторы псевдослучайных чисел склоны зацикливаться. Это значит, что средствами компьютера можно сгенерировать лишь ограниченное количество псевдослучайных чисел. Цикл генератора псевдослучайных чисел в `python` составляет $2^{19937}-1$, чего хватает во многих случаях.    
```

Теперь проиллюстрируем, что псевдослучайные числа все же отличаются от случайных тем, что они являются результатом детерминированных и воспроизводимых вычислений. Это значит, что мы можем запомнить состояние генератора псевдослучайных чисел, сгенерировать последовательность чисел, вернуться к запомненному состоянию, сгенерировать ещё одну последовательность, и в итоге две сгенерированные последовательности в точности совпадут. Код в ячейке ниже иллюстрирует этот факт.     

In [5]:
state = random.getstate()
y = random_numbers(5)
print(y)

random.setstate(state)
z = random_numbers(5)
print(z)

[0.5053552881033624, 0.026535969683863625, 0.1988376506866485, 0.6498844377795232, 0.5449414806032167]
[0.5053552881033624, 0.026535969683863625, 0.1988376506866485, 0.6498844377795232, 0.5449414806032167]


С генератором настоящих случайных чисел такое невозможно принципиально, иначе эти числа нельзя считать случайными. 

Итого, генератор псевдослучайных чисел генерирует ограниченную последовательность чисел детерминированным и воспроизводимым образом, которую практически невозможно отличить статистическими методами от последовательности поистине случайных чисел.

## Генерация псевдослучайных чисел в `NumPy`

Помимо [random.random](https://docs.python.org/3/library/random.html#random.random) модуль [random](https://docs.python.org/3/library/random.html) стандартной библиотеки `python` содержит большое количество других методов, генерирующих псевдослучайные числа, например, из нормального, экспоненциального, дискретных и многих других распределений. Однако все эти методы генерируют одно число за раз, да и возвращают числовой объект одного из встроенных типов. Если вы итак уже работаете с `NumPy`, то для генерации псевдослучайных чисел практичнее воспользоваться средствами самой библиотеки, а конкретно её модуля `numpy.random`. Например, следующий код генерирует сразу 5 случайных чисел в диапазоне от 0 до 1 однократным вызовом метода [random](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html).

In [6]:
import numpy as np

x = np.random.random(size=5)
print(x)

[0.60544416 0.52443577 0.04882692 0.3960846  0.87648535]


Однако разработчики `NumPy` рекомендуют не пользоваться методами модуля `numpy.random` непосредственно, а создавать объект генератора случайных чисел и вызывать методы генерации случайных чисел от него. 

Самый естественный способ создания объекта генератора случайных чисел --- метод [numpy.random.default_rng](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.default_rng).

In [7]:
rng = np.random.default_rng()

После того, как этот объект создан, его методы используются для генерации псевдослучайных чисел. Например, чтобы сгенерировать случайное число по биномиальному распределению с параметрами $n$ и $p$, необходимо вызвать метод [binomial](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.binomial.html) этого объекта генератора.

In [15]:
x = rng.binomial(n=10, p=0.5)
print(x)

5


Все методы генерации псевдослучайных чисел в `NumPy` по умолчанию генерируют одно число, но каждый из них имеет опциональный параметр `size`, который позволяет сгенерировать сразу массив случайных чисел. 

In [12]:
x = rng.normal(loc=10, scale=1, size=5)
print(x)

[ 9.80286467 12.70002888  9.73240799 11.48288419  8.50291919]


При этом в качестве параметра `size` можно указать кортеж значений, если требуется сгенерировать не одномерный массив случайных чисел. 

In [14]:
x = rng.poisson(lam=1.0, size=(5, 5))
print(x)

[[0 1 2 1 3]
 [0 0 0 1 3]
 [0 0 2 1 0]
 [0 1 1 1 3]
 [1 2 2 1 0]]


Вероятность генерации тех или иных значений определяется [распределением вероятностей](https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D1%81%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2%D0%B5%D1%80%D0%BE%D1%8F%D1%82%D0%BD%D0%BE%D1%81%D1%82%D0%B5%D0%B9#:~:text=%D0%A0%D0%B0%D1%81%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%B2%D0%B5%D1%80%D0%BE%D1%8F%D1%82%D0%BD%D0%BE%D1%81%D1%82%D0%B5%D0%B9%20%E2%80%94%20%D1%8D%D1%82%D0%BE%20%D0%B7%D0%B0%D0%BA%D0%BE%D0%BD%2C%20%D0%BE%D0%BF%D0%B8%D1%81%D1%8B%D0%B2%D0%B0%D1%8E%D1%89%D0%B8%D0%B9,%D1%81%D0%BE%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D1%83%D1%8E%D1%89%D0%B8%D0%B5%20%D0%B2%D0%B5%D1%80%D0%BE%D1%8F%D1%82%D0%BD%D0%BE%D1%81%D1%82%D0%B8%20%D0%BF%D0%BE%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F%20%D1%8D%D1%82%D0%B8%D1%85%20%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B9.). Все доступные в `NumPy` распределения перечисленны по [ссылке](https://numpy.org/doc/stable/reference/random/generator.html#distributions). Ещё более широкий спектр распределений доступен в модуле [stats](https://docs.scipy.org/doc/scipy/reference/stats.html#probability-distributions) библиотеки [SciPy](https://scipy.org/).